feat:Banner UI
chubinaaa/artoa-FE pull request #53
Opened 2024-11-20 16:56 UTC by IzaDoliashvili

# Pull Request Template for ArtOa

## Description

Please provide a summary of the changes in this pull request:

- What does this PR do?
- Why are these changes necessary?
- Any relevant links or references?

Fixes: [issue number/link]

---

## Type of Change

Please select the type of change this PR introduces (tick the appropriate box):

- [ ] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [ ] 🔄 Refactor (code or file structure changes without affecting functionality)
- [ ] 📝 Documentation update (changes or additions to documentation)
- [ ] 🚀 Performance improvement (optimization in code or resources)

---

## Checklist

Please ensure the following tasks have been completed before requesting a review:

- [ ] My code follows the style guidelines of this project
- [ ] I have run tests to ensure my changes work as expected
- [ ] I have added/updated necessary tests or documentation (if applicable)
- [ ] I have self-reviewed my code and refactored any areas that need improvement
- [ ] There are no console errors or warnings related to my changes
- [ ] The PR includes a clear, detailed title and description
- [ ] Any relevant issues have been linked or mentioned in this PR
- [ ] I have reviewed the acceptance criteria and met all requirements
- [ ] I have considered edge cases and errors that may occur due to my changes

---

## Testing Instructions

Please describe how your changes can be tested:

1. **Test Setup:** (Any steps for environment setup)
2. **Test Steps:**
   - Step 1: ...
   - Step 2: ...
   - ...

---

## Screenshots / Visual Changes

Please attach any relevant screenshots, videos, or GIFs to illustrate the impact
of this change (if applicable).

---

## Additional Notes

Is there anything else the reviewer should know about this PR? Any known issues,
challenges, or decisions made during implementation?

2024-11-24 08:09 UTC, mshubitidze requested changes
very clean code, although ui doesnt match the figma design

2024-11-24 08:09 UTC, mshubitidze commented on src/app/banner/page.tsx
> +    <section className="relative bg-cover bg-center text-white">
text-white is unnecessary here, text color is already being set on all elements in globals.css file

2024-11-24 08:09 UTC, mshubitidze commented on src/app/banner/page.tsx
> +        style={{ backgroundImage: "url('/banner/image/Mask.png')" }}
this is completely fine, although i'd inline this style as a tailwind class: `bg-[url('/banner/image/Mask.png')]`

2024-11-24 08:09 UTC, mshubitidze commented on src/app/banner/page.tsx
> +        <div className="bg-black/70 px-8 py-16">
background mask is already present in the image uploaded, adding bg-black/70 is unnecessary here
<img width="1120" alt="Screenshot 2024-11-24 at 12 05 57" src="https://github.com/user-attachments/assets/bd602598-f0bb-4d23-b3b7-2750f043063d">

2024-11-24 08:09 UTC, mshubitidze commented on src/app/banner/page.tsx
> +            <p className="text-2xl font-bold md:text-3xl">70+</p>
font sizes and the layout dont look right
<img width="1120" alt="Screenshot 2024-11-24 at 12 05 57" src="https://github.com/user-attachments/assets/7c63a8ce-91bd-492c-8561-6fe4e0c1c1fb">

2024-11-24 08:09 UTC, mshubitidze commented on src/app/banner/page.tsx
> +            <div className="my-6 flex flex-col items-start gap-y-1 text-lg leading-relaxed md:text-xl">
this layout is close but can me adjusted to be much more similar to the figma design
![Uploading Screenshot 2024-11-24 at 12.05.57.png…]()

2024-11-25 14:29 UTC, IzaDoliashvili commented
I have some problems with the background image on mobile version. Please check it.

2024-11-25 15:29 UTC, mshubitidze commented
> I have some problems with the background image on mobile version. Please check it.

i think its because the div with bg-[url(image)] class doesnt have bg-cover class

2024-11-26 07:53 UTC, merged