Feat/team section
chubinaaa/artoa-FE pull request #57
Opened 2024-11-23 17:26 UTC by rolandiartmeladze

# Pull Request Template for ArtOa
!! not marg yet not finish 

## Description

Please provide a summary of the changes in this pull request:

- What does this PR do?
- Why are these changes necessary?
- Any relevant links or references?

Fixes: [issue number/link]

---

## Type of Change

Please select the type of change this PR introduces (tick the appropriate box):

- [ ] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ x ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [ ] 🔄 Refactor (code or file structure changes without affecting functionality)
- [ ] 📝 Documentation update (changes or additions to documentation)
- [ ] 🚀 Performance improvement (optimization in code or resources)

---

## Checklist

Please ensure the following tasks have been completed before requesting a review:

- [ x ] My code follows the style guidelines of this project
- [ ] I have run tests to ensure my changes work as expected
- [ ] I have added/updated necessary tests or documentation (if applicable)
- [ ] I have self-reviewed my code and refactored any areas that need improvement
- [ ] There are no console errors or warnings related to my changes
- [ ] The PR includes a clear, detailed title and description
- [ ] Any relevant issues have been linked or mentioned in this PR
- [ ] I have reviewed the acceptance criteria and met all requirements
- [ ] I have considered edge cases and errors that may occur due to my changes

---

## Testing Instructions

Please describe how your changes can be tested:

1. **Test Setup:** (Any steps for environment setup)
2. **Test Steps:**
   - Step 1: ...
   - Step 2: ...
   - ...

---

## Screenshots / Visual Changes

Please attach any relevant screenshots, videos, or GIFs to illustrate the impact
of this change (if applicable).

---

## Additional Notes

Is there anything else the reviewer should know about this PR? Any known issues,
challenges, or decisions made during implementation?

2024-11-24 08:00 UTC, mshubitidze requested changes
overall, good work, can use some cleanup tho

2024-11-24 08:00 UTC, mshubitidze commented on src/config/team.ts
> +export const TeamConfig = [
this variable should be lowercase

2024-11-24 08:00 UTC, mshubitidze commented on src/config/team.ts
> +    image: teamImage2,
instead of image, this can be `href` which directly points to the public folder `/team/image1.svg|png`

2024-11-24 08:00 UTC, mshubitidze commented on src/types/employee.ts
creating a separate type for an employee card doesnt really make sense here, we can just infer it from the teamConfig object if necessary, eg.: type Employee = TeamConfig[number]

2024-11-24 08:00 UTC, mshubitidze commented on src/config/team.ts
> +import teamImage1 from "@/../public/team1.svg";
this is incorrect import syntax, not necessary either

2024-11-24 08:00 UTC, mshubitidze commented on src/components/homepage/artoa-team-section.tsx
> +  const teamMembers = Object.values(TeamConfig);
why are we using Object.values here?
you can just map over the teamConfig array directly

2024-11-24 08:00 UTC, mshubitidze commented on src/components/ui/team.tsx
good job figuring out forwardRef!
except in case of team member cards, it might not be necessary to create a reusable component since it will not be used anywhere but the TeamSection

2024-11-24 08:00 UTC, mshubitidze commented on src/components/ui/team.tsx
> +  <div ref={ref} className={cn("p-4 pt-0", className)} {...props} />
why are you setting default padding here, just to remove it when using this component in team-card.tsx?

2024-11-28 10:36 UTC, chubinaaa approved these changes

2024-11-28 11:31 UTC, merged